environments:
  - name: dev
    configs:
      endpoints:
          production:
              url: 'https://petstore.swagger.io/v2/'
      deploymentEnvironments:
          - displayOnDevportal: true
            deploymentEnvironment: Default
            deploymentVhost : 172.20.138.214
